services:
  gig_finder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gig_finder
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
    volumes:
      - ./gig_finder:/app
    command: scrapy crawl freelancer